<?php
/**
 * Standalone proof of TC_Platform_Sync's webhook signature verification —
 * no WordPress, no HTTP, no database. Run from anywhere:
 *
 *     php wp-content/plugins/together-clinic-eligibility/tests/platform-sync-smoke-test.php
 *
 * TC_Platform_Sync::verify_signature() must accept exactly what
 * `packages/contracts/src/signature.ts` (the prescribing platform's own
 * signer) produces, and reject anything a real delivery would not send:
 * a stale timestamp, a tampered body, a tampered signature, and a header
 * that isn't shaped `t=<digits>,v1=<64 hex>`.
 *
 * The known-good vector below was generated by running the ACTUAL
 * TypeScript implementation (not hand-derived), from the platform repo:
 *
 *     cd packages/contracts && node -e '
 *       const { createHmac } = require("crypto");
 *       const secret = "whsec_test_platform_sync_harness_only";
 *       const timestamp = 1758374400;
 *       const body = JSON.stringify({
 *         id: "5b1b6c1a-2222-4f33-9b11-0f1a2b3c4d5e",
 *         type: "prescription.issued",
 *         occurredAt: "2026-09-20T14:40:00.000Z",
 *         tenantId: "9c858901-8a57-4791-81fe-4c455b099bc9",
 *         data: {
 *           prescriptionId: "9c858901-8a57-4791-81fe-4c455b099bc9",
 *           patientId: "9c858901-8a57-4791-81fe-4c455b099bc9",
 *           externalReference: "501",
 *           code: "ABCD-EFGH-JKMN",
 *           status: "ISSUED"
 *         }
 *       });
 *       console.log(createHmac("sha256", secret).update(`${timestamp}.${body}`, "utf8").digest("hex"));
 *     '
 *   → 02f0cc025833e5ec07ff7f3077166dd7bcc207dcc9242ece376fdb1d647fb119
 *
 * This is `signWebhookBody()`'s own algorithm
 * (`createHmac("sha256", secret).update(`${timestamp}.${body}`, "utf8")`),
 * confirmed against `verifyWebhookSignature()` in the same run (returned
 * `true`) before being pasted here — see the P6 build report for the full
 * node invocation and its output.
 */

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', sys_get_temp_dir() . '/' ); // satisfy the plugin file guard
}
// No other WordPress constant or function needs defining here: retry_delays()
// (Opus review, minor 8) reads MINUTE_IN_SECONDS at call time with its own
// fallback rather than a class constant's compile-time expression, so this
// file loads standalone with nothing else set up first.

require __DIR__ . '/../includes/class-tc-platform-sync.php';

$pass = 0;
$fail = 0;
function check( $label, $cond ) {
	global $pass, $fail;
	if ( $cond ) { $pass++; echo "  PASS  $label\n"; }
	else { $fail++; echo "  FAIL  $label\n"; }
}

// ---------------------------------------------------------------------------
// The known-good vector, verbatim from packages/contracts/src/signature.ts.
// ---------------------------------------------------------------------------

$secret    = 'whsec_test_platform_sync_harness_only';
$timestamp = 1758374400;
$body      = '{"id":"5b1b6c1a-2222-4f33-9b11-0f1a2b3c4d5e","type":"prescription.issued","occurredAt":"2026-09-20T14:40:00.000Z","tenantId":"9c858901-8a57-4791-81fe-4c455b099bc9","data":{"prescriptionId":"9c858901-8a57-4791-81fe-4c455b099bc9","patientId":"9c858901-8a57-4791-81fe-4c455b099bc9","externalReference":"501","code":"ABCD-EFGH-JKMN","status":"ISSUED"}}';
$signature = '02f0cc025833e5ec07ff7f3077166dd7bcc207dcc9242ece376fdb1d647fb119';
$header    = 't=' . $timestamp . ',v1=' . $signature;

echo "\n— TypeScript-generated vector verifies —\n";
check(
	'a genuine signature from packages/contracts/src/signature.ts verifies',
	TC_Platform_Sync::verify_signature( $header, $body, $secret, $timestamp )
);
check(
	'the header name matches WEBHOOK_SIGNATURE_HEADER (X-Together-Signature)',
	TC_Platform_Sync::SIGNATURE_HEADER === 'X-Together-Signature'
);

echo "\n— tamper detection —\n";
$tampered_body = str_replace( 'ISSUED', 'CANCELLED', $body );
check(
	'a tampered body is rejected',
	! TC_Platform_Sync::verify_signature( $header, $tampered_body, $secret, $timestamp )
);

$tampered_sig    = substr( $signature, 0, -1 ) . ( '0' === substr( $signature, -1 ) ? '1' : '0' );
$tampered_header = 't=' . $timestamp . ',v1=' . $tampered_sig;
check(
	'a tampered signature is rejected',
	! TC_Platform_Sync::verify_signature( $tampered_header, $body, $secret, $timestamp )
);

check(
	'the wrong secret is rejected',
	! TC_Platform_Sync::verify_signature( $header, $body, 'wrong-secret', $timestamp )
);

echo "\n— replay protection (five-minute tolerance) —\n";
check(
	'just inside the five-minute window verifies',
	TC_Platform_Sync::verify_signature( $header, $body, $secret, $timestamp + 299 )
);
check(
	'just outside the five-minute window is rejected',
	! TC_Platform_Sync::verify_signature( $header, $body, $secret, $timestamp + 301 )
);
check(
	'a delivery from the future outside the window is also rejected',
	! TC_Platform_Sync::verify_signature( $header, $body, $secret, $timestamp - 301 )
);

echo "\n— malformed header rejection —\n";
check( 'an empty header is rejected', ! TC_Platform_Sync::verify_signature( '', $body, $secret, $timestamp ) );
check( 'a missing header is rejected', ! TC_Platform_Sync::verify_signature( null, $body, $secret, $timestamp ) );
check(
	'a header with no v1 component is rejected',
	! TC_Platform_Sync::verify_signature( 't=' . $timestamp, $body, $secret, $timestamp )
);
check(
	'a header with a short (truncated) signature is rejected',
	! TC_Platform_Sync::verify_signature( 't=' . $timestamp . ',v1=deadbeef', $body, $secret, $timestamp )
);
check(
	'a header with an uppercase signature is rejected (hex must be lowercase, matching the TS output)',
	! TC_Platform_Sync::verify_signature( 't=' . $timestamp . ',v1=' . strtoupper( $signature ), $body, $secret, $timestamp )
);
check(
	'a completely different signature scheme (Stripe-style, no v1=) is rejected',
	! TC_Platform_Sync::verify_signature( 't=' . $timestamp . ',s=' . $signature, $body, $secret, $timestamp )
);

echo "\n— an empty configured secret always refuses (fail closed) —\n";
check(
	'an empty secret is never satisfied, even by an otherwise well-formed header',
	! TC_Platform_Sync::verify_signature( $header, $body, '', $timestamp )
);

echo "\n— country normalisation (patient-request mapping) —\n";
$normalise = new ReflectionMethod( 'TC_Platform_Sync', 'normalise_country' );
$normalise->setAccessible( true );
check( 'England maps to ENGLAND', $normalise->invoke( null, 'England' )[0] === 'ENGLAND' );
check( 'Scotland maps to SCOTLAND', $normalise->invoke( null, 'Scotland' )[0] === 'SCOTLAND' );
check( 'Wales maps to WALES', $normalise->invoke( null, 'wales' )[0] === 'WALES' );
check( 'Northern Ireland maps to NORTHERN_IRELAND', $normalise->invoke( null, 'Northern Ireland' )[0] === 'NORTHERN_IRELAND' );
check( 'England is not flagged for review', $normalise->invoke( null, 'England' )[1] === false );
check( '"United Kingdom" defaults to ENGLAND, flagged for review', $normalise->invoke( null, 'United Kingdom' ) === [ 'ENGLAND', true ] );
check( 'blank defaults to ENGLAND, flagged for review', $normalise->invoke( null, '' ) === [ 'ENGLAND', true ] );
check( 'garbage defaults to ENGLAND, flagged for review', $normalise->invoke( null, 'Mars' ) === [ 'ENGLAND', true ] );

echo "\n— dob normalisation —\n";
$normalise_dob = new ReflectionMethod( 'TC_Platform_Sync', 'normalise_dob' );
$normalise_dob->setAccessible( true );
check( 'an already-ISO date passes through unchanged', $normalise_dob->invoke( null, '1990-05-14' ) === '1990-05-14' );
check( 'an unambiguous non-ISO date is normalised to ISO', $normalise_dob->invoke( null, '14 May 1990' ) === '1990-05-14' );
check( 'an empty dob stays empty (never invented)', $normalise_dob->invoke( null, '' ) === '' );
check( 'unparseable garbage returns empty rather than throwing', $normalise_dob->invoke( null, 'not-a-date-at-all-xyz' ) === '' );
// PHP's DateTime parses a slash-separated date as US m/d/Y (never UK
// d/m/Y), so an out-of-range "month" like 14 throws rather than silently
// producing the wrong date — exactly the fail-closed behaviour wanted here.
check(
	'an ambiguous slash-separated date PHP cannot parse safely returns empty, not a guess',
	$normalise_dob->invoke( null, '14/05/1990' ) === ''
);

echo "\n— externalReference namespacing (Opus review, M1) —\n";
$order_id_from_ref = new ReflectionMethod( 'TC_Platform_Sync', 'order_id_from_external_reference' );
$order_id_from_ref->setAccessible( true );
check( 'a namespaced reference resolves to the order id', $order_id_from_ref->invoke( null, 'tc-order-501' ) === 501 );
check( 'a namespaced reference with a large id still resolves', $order_id_from_ref->invoke( null, 'tc-order-999999' ) === 999999 );
check(
	'a bare numeric reference (the old, unnamespaced shape) is refused, not silently accepted',
	$order_id_from_ref->invoke( null, '501' ) === null
);
check( 'an empty reference is refused', $order_id_from_ref->invoke( null, '' ) === null );
check( 'a reference from an unrelated namespace is refused', $order_id_from_ref->invoke( null, 'other-order-501' ) === null );
check( 'a non-numeric suffix is refused', $order_id_from_ref->invoke( null, 'tc-order-abc' ) === null );
check( 'trailing garbage after the id is refused', $order_id_from_ref->invoke( null, 'tc-order-501x' ) === null );

echo "\n========================================\n";
echo "  $pass passed, $fail failed\n";
echo "========================================\n";
exit( $fail === 0 ? 0 : 1 );
